### ISSUE TITLE
sass: not found + path issue

### ISSUE THREAD

**Issue by UnitedPE** [LINKIWI/endpoint#1]
Ubuntu 16.04
node 7.2.1
npm 3.10.10

After installing all packages. The build command failed.

```bash
$ npm run build

> endpoint@1.0.0 build /endpoint
> npm run build-css && npm run build-js


> endpoint@1.0.0 build-css /endpoint
> mkdir -p src/client/static/dist && sass --style compressed src/client/styles/scss/main.scss:src/client/static/dist/stylesheet.css

sh: 1: sass: not found

.....
```

I fixed this issues by installing a aproitated package. Then I run into the next issue. Webpack can not find the file `../config/secrets`. 
```bash
> endpoint@1.0.0 build-js /home/badry/Projekte/upe/endpoint
> mkdir -p src/client/static/dist && webpack --config config/webpack.js

Hash: 6f19e4fe502be799a639
Version: webpack 1.14.0
Time: 5099ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.71 MB       0  [emitted]  bundle
    + 471 hidden modules

ERROR in ./src/client/app/app.js
Module not found: Error: Cannot resolve 'file' or 'directory' ../config/secrets in /home/badry/Projekte/upe/endpoint/src/client/app
 @ ./src/client/app/app.js 42:15-43
```

Then i try to start the app but:
```bash
$ npm run start

> endpoint@1.0.0 start /home/badry/Projekte/upe/endpoint
> node index.js

module.js:472
    throw err;
    ^

Error: Cannot find module '../../config/secrets'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/badry/Projekte/upe/endpoint/src/server/index.js:15:1)
    at Module._compile (module.js:571:32)
    at loader (/home/badry/Projekte/upe/endpoint/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/badry/Projekte/upe/endpoint/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/badry/Projekte/upe/endpoint/index.js:3:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

After i fixed the path in `src/server/index.js`, the app starts and works.

**Comment by LINKIWI** [comment]
Thanks for pointing this out. I forgot to add some documentation in the README about sass and secrets.js. I will fix.

Also note that secrets.js is optional. Currently it's only used to store Sentry DSNs, but if Sentry is not part of your infrastructure or you don't need any error reporting, you can use just use the provided secrets.js.template without modification.
